---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: configuration file copying 
      ansible.builtin.copy:
        src: ansible.iphilka.ru.conf
        dest: /etc/nginx/sites-available/ansible.iphilka.ru.conf
        mode: '0644'

    - name: link creation in sites-enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/ansible.iphilka.ru.conf
        dest: /etc/nginx/sites-enabled/ansible.iphilka.ru.conf
        state: link
        mode: '0644'

    - name: create directory stud-template directory
      ansible.builtin.file:
        path: /home/ansible-worker/www/stud-template
        state: directory

    - name: copy index.html file
      ansible.builtin.copy:
        src: "index.html"
        dest: "/home/ansible-worker/www/stud-template/index.html"
        mode: '0644'
        